### ISSUE TITLE
Qt translation files are missed from OS X bundle

### ISSUE THREAD

**Issue by sikmir** [tumic0/GPXSee#116] opened 2018-05-21 17:05 UTC
https://github.com/tumic0/GPXSee/blob/ba7074f9021960776af015e0fc52e0b4f6097d45/src/GUI/app.cpp#L25-L32
```bash
$ ls /Applications/GPXSee.app/Contents/Resources/translations/qt_*.qm 2>/dev/null | wc -l
0
```

**Comment by tumic0** [comment] 2018-05-21 19:07
The problem with the translations on Mac is that the default TextHeuristicRole of the menus is broken by design which leads to very strange things like disappearing menus as described in [QTBUG-30812](https://bugreports.qt.io/browse/QTBUG-30812). Not including the QT translation files is a kind of workaround - the problems disappear when they are not used. A better workaround would be manually setting the role on every menu  item like I have seen in some applications, but this has to be done...

Or QT could finally fix it :-)

**Comment by tumic0** [comment] 2018-07-21 21:36
Explicit menu roles added in 476f26752f9da9aee31384de2d55b195b731026d and everything seems to work, so starting with 5.16 the qt translation files will be included in the app bundle.

**Closed by tumic0** 2018-07-21 21:36 UTC
