### ISSUE TITLE
Add giant "Download from  Google Play" button

### ISSUE THREAD

**Issue by jidanni** [tumic0/GPXSee#465] opened 2022-12-14 22:32 UTC
On https://www.gpxsee.org/index.html#download there is just this passing mention 
> On Android, you can install GPXSee from the Google Play app store.

And then the user is supposed to go searching around for it there.

But other apps always have this giant banner link for downloading them from Google Play.

So perhaps there could be a at least a hyperlink provided as a compromise, to help users find their way.

The link is in #466.

**Comment by tumic0** [comment] 2022-12-15 00:10
Closing this as a duplicate of #466

**Closed by tumic0** 2022-12-15 00:10 UTC
