### ISSUE TITLE
FR: Graph any available user activity data

### ISSUE THREAD

**Issue by zaddi** [tumic0/GPXSee#523] opened 2023-10-25 05:12 UTC
It'd be great to be able to view graphs of data logged to custom activity fields.  Arbitrary numeric values such as battery level, vehicle count, tire pressure or beers earned which can be recorded by Garmin apps/datafields.  These data fields could be automatically discovered in the .fit file and added as graph tabs.

And having the ability to overlay multiple values on a plot would be very helpful. For example to see the correlation between elevation, heart rate & beers earned :-)

**Comment by tumic0** [comment] 2023-10-26 00:10
Duplicate of #499

**Closed by tumic0** 2023-10-26 00:10 UTC
