### ISSUE TITLE
Keyboard control for slider in graph

### ISSUE THREAD

**Issue by nick51** [tumic0/GPXSee#360] opened 2021-04-07 09:14 UTC
The slider in the graph window can be moved using the mouse, and the associated position along the track is indicated with a red '+'. That is a very useful feature, but it is difficult to position the slider precisely using the mouse. Especially on laptop with a trackpad. Would it be possible also to allow the use of left and right arrows on the keyboard to move the slider more precisely?

**Comment by tumic0** [comment] 2021-04-07 21:25
Duplicate of #359

**Closed by tumic0** 2021-04-07 21:25 UTC
