### ISSUE TITLE
Temperature shows dual degree symbol

### ISSUE THREAD

**Issue by tonyrulez** [tumic0/GPXSee#472] opened 2022-12-31 08:12 UTC
Version: 11.11 on Windows 10

When viewing the temperature graph or statistics windows, temperature is shown with **°°C** instead of **°C**

![kép](https://user-images.githubusercontent.com/27233005/210130132-435efc74-c61d-47af-9fd6-5a74423245a8.png)
![kép](https://user-images.githubusercontent.com/27233005/210130135-0ceec699-fcd1-4291-8e4d-d5058fbfbaa1.png)

**Comment by tumic0** [comment] 2023-01-01 15:57
The issue was caused by a broken Hungarian translation, fixed in 29895420b629b1c2000ed028b5f708fe137c4bc0. You can fix the translations as well as add any missing strings directly on the project's [Weblate page](https://hosted.weblate.org/projects/gpxsee/translations/).

**Closed by tumic0** 2023-01-01 15:57 UTC
