### ISSUE TITLE
Qt dependency issues with Ubuntu and Fedora packages

### ISSUE THREAD

**Issue by eddy-geek** [tumic0/GPXSee#342] opened 2021-02-09 17:38 UTC
Hello,

Some issues with `gpxsee Version: 8.4-1` deb package in standard Ubuntu LTS install (focal 20.04):

* ~A lot of file formats are not supported in Ubuntu~ I just mistook *File > Open* for *Map > Load map*

* The Ubuntu package depends on `qtbase-abi-5-12-8` although not present nor needed in Ubuntu. I was able to work around it as [here](https://serverfault.com/questions/250224/how-do-i-get-apt-get-to-ignore-some-dependencies):
  * Download deb package eg `wget https://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_20.10/amd64/gpxsee_8.5-1_amd64.deb`
  * `sudo dpkg -i --ignore-depends=qtbase-abi-5-12-8 ./gpxsee_8.4-1_amd64.deb`
  * Remove `, qtbase-abi-5-12-8` from `sudo vim /var/lib/dpkg/status` 

Thanks for this great tool!

**Comment by eddy-geek** [comment] 2021-02-09 18:19
Similar issues on fedora 33

```bash
cat /etc/fedora-release
# Fedora release 33 (Thirty Three)
rpm -i ./gpxsee-8.5-4.1.x86_64.rpm
# error: Failed dependencies:
#        libQt5Gui.so.5(Qt_5.15.1_PRIVATE_API)(64bit) is needed by gpxsee-8.5-4.1.x86_64
rpm -q qt5-qtbase-gui
# qt5-qtbase-gui-5.15.2-2.fc33.x86_64
```

In this case forcing ahead with `--nodeps` yields a similar. runtime error.
Of course fedora has a built-in package, but it's at 7.36 :disappointed:

**Comment by tumic0** [comment] 2021-02-09 19:44
Hi,
I suppose that the problem is caused by the openSUSE Build Service having not yet updated the packages in Fedora and Ubuntu. From what I see in the [Fedora 33 build log](https://build.opensuse.org/package/live_build_log/home:tumic:GPXSee/gpxsee/Fedora_33/x86_64) , the package was build against Qt 5.15.1. So you have generally 3 choices:

1. Compile the package yourself.
2. Install it with some kind of "force" flag (it will work, there were no changes in the API for the last 10 years).
3. Wait until openSUSE Build Service updates and recompiles the packages.

**Comment by tumic0** [comment] 2021-03-02 19:42
Closing. You may report the not updated distributions as a bug to the OBS instance bugs reporting place which is the [OpenSuse bugzilla](https://bugzilla.opensuse.org/). There is nothing I can do about it.

**Closed by tumic0** 2021-03-02 19:42 UTC

**Comment by eddy-geek** [comment] 2021-11-10 10:15
**Focusing on the Ubuntu issue**

Asking for reopening.

```
$ sudo apt install gpxsee
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 gpxsee : Depends: qtbase-abi-5-15-2 but it is not installable
```

**Comment by tumic0** [comment] 2021-11-10 10:51
I have checked it and the Ubuntu 20.04 package from OBS has no qtbase-abi-5-15-2 dependency. Most probably you are trying to install the Ubuntu 21.04 package which has qtbase-abi-5-15-2 dependency.

**Comment by eddy-geek** [comment] 2021-11-10 11:33
Sorry, I indeed pasted the wrong snippet after testing several packages.  The issue is with the `qtbase-abi-5-12-8` which is the version that the 20.04 version comes with.

```sh
$ grep REL /etc/lsb-release
DISTRIB_RELEASE=20.04
$ wget http://download.opensuse.org/repositories/home:/tumic:/GPXSee/xUbuntu_20.04/amd64/gpxsee_9.11-1_amd64.deb -O $ /usr/bin/ar x gpxsee_9.11-1_amd64_focal.deb
$ tar -xvf control.tar.xz        
$ grep Depends control
Depends: libc6 (>= 2.29), libgcc-s1 (>= 3.0), libqt5concurrent5 (>= 5.6.0~rc), libqt5core5a (>= 5.12.2), libqt5gui5 (>= 5.11.0~rc1) | libqt5gui5-gles (>= 5.11.0~rc1), libqt5network5 (>= 5.9.0~beta), libqt5printsupport5 (>= 5.0.2), libqt5sql5 (>= 5.0.2), libqt5widgets5 (>= 5.3.0), libstdc++6 (>= 5), qtbase-abi-5-12-8

$sudo dpkg -i gpxsee_9.11-1_amd64_focal.deb
gpxsee depends on qtbase-abi-5-12-8; however:
  Package qtbase-abi-5-12-8 is not installed.
```

However I just realized the cause of my issue is using [KDE neon](https://neon.kde.org) distro which overrides Ubuntu 20.04's Qt.

```
$ sudo apt install qtbase-abi-5-12-8
Package qtbase-abi-5-12-8 is a virtual package provided by:
  libqt5core5a 5.12.8+dfsg-0ubuntu1 [Not candidate version]

$ apt show libqt5core5a
Version: 5.15.2+p20.04+tunstable+git20211108.1805-0
Maintainer: Neon CI <neon@kde.org>
```

So, sorry for the noise.
