### ISSUE TITLE
Starting record with a Garmin devices

### ISSUE THREAD

**Issue by cyclobing** [tumic0/GPXSee#572] opened 2024-10-29 09:45 UTC
When a Garmin device (for example Edge 830) can be set to the altitude of the starting point, the first record is not this one. The second record has the altitude of that point.
That explain the difference between the altitude indicated by GPXSee and the one of Garmin Connect.
**Could you introduce a new parameter or setting that say "Ignore the first record" ?**
Thank you.
By the way I can prove that Garmin devices display the altitude computed with GPS signal but record the altitude according to the barometer. This is just crazy and unreliable ! !

**Comment by tumic0** [comment] 2024-10-29 19:26
Please provide some real sample files so I can look at them and decide what can be done.

**Comment by cyclobing** [comment] 2024-10-30 09:05
> Please provide some real sample files so I can look at them and decide what can be done.

I have seen the problem on GPX file.
Do you prefer original FIT files or just the first records of GPX files ?

**Comment by tumic0** [comment] 2024-10-30 09:20
The file where it occurs. If it is a GPX file exported using some Garmin tool from a FIT file, then the original FIT file would be "nice to have" to get more info about the problem.

**Comment by cyclobing** [comment] 2024-10-30 15:25
Good Evening,

 

It occurs in all files since many years. It took me a rather long time since I could understand and then decide to write to you.

 

I send you my 4 last *.fit files and a PDF of an Excel spread sheet where you can see the problem and also other differences with altitudes of Garmin comparing to an old Ciclosport CM436Mwihich is much more reliable ! !

 

Do you remember that I was asking you in 2022/2021 why it is impossible to copy the statistics in the windows after Ctrl+s ?

 

Thank you in advance

 

Best regards.

 

Blaise Dériaz
8, rue du Vieux-Collège
CH - 1204  Genève
+41 22 311 60 53  tél.
+41 22 320 03 17  bur.
+41 79 379 33 63  mobile

  _____  

De : Martin Tůma ***@***.*** 
Envoyé : mercredi, 30 octobre 2024 10:21
À : tumic0/GPXSee
Cc : cyclobing; Author
Objet : Re: [tumic0/GPXSee] Starting record with a Garmin devices (Issue #572)

 

The file where it occurs. If it is a GPX file exported using some Garmin tool from a FIT file, then the original FIT file would be "nice to have" to get more info about the problem.

**Comment by tumic0** [comment] 2024-11-04 01:25
As you can see on the issue web page, nothing has been included. Without the data, there is nothing to do...

**Comment by cyclobing** [comment] 2024-11-04 08:40
I do not understand *without data" because I sent you 4 fit files ans a PDF.
I tried again directly here and I got this message :

We don’t support that file type.
Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

GPXSee is for fit or gpx files or other files formats which are not listed above. Where is the bug ?

**Comment by tumic0** [comment] 2024-11-04 08:53
1. It's not a bug, it's a feature! Usually you have to ZIP the attachments here on GitHub (don't ask me why).
2. I definitely need the original FIT or GPX files, PDF exports are useless for me.

**Comment by cyclobing** [comment] 2024-11-04 09:07
Now it should be OK.

 

PDF is a just an overview of the first recorded altitudes by Edge 830 compared with the more accurate Ciclosport CM436M !

 

Blaise

  _____  

De : Martin Tůma ***@***.*** 
Envoyé : lundi, 4 novembre 2024 09:54
À : tumic0/GPXSee
Cc : cyclobing; Author
Objet : Re: [tumic0/GPXSee] Starting record with a Garmin devices (Issue #572)

 

1.	It's not a bug, it's a feature! Usually you have to ZIP the attachments here on GitHub (don't ask me why).
2.	I definitely need the original FIT or GPX files, PDF exports are useless for me.

**Comment by tumic0** [comment] 2024-11-06 07:16
Closing due to no sample data received.

**Closed by tumic0** 2024-11-06 07:16 UTC

**Comment by cyclobing** [comment] 2024-11-06 08:53
I wonder why you do not get data I sent you twice.
Here again
[Activities.zip](https://github.com/user-attachments/files/17644299/Activities.zip)

**Comment by tumic0** [comment] 2024-11-07 01:56
Ok, now the data is here, but I do not see any significant difference between the first and second points, the difference is < 15m on all the tracks. Is it that 10-15m that is bothering you?
