### ISSUE TITLE
vary track colour by value

### ISSUE THREAD

**Issue by shiroyagi** [tumic0/GPXSee#471] opened 2022-12-21 20:20 UTC
Currently the track colour is constant (default blue), it would be useful to be able to select a variable (speed, heart rate, distance or time from the start etc) so that the hue varies according to the normalised value.  The graph cursor is useful, but this would be better in some situations, eg. self-intersecting tracks where the order of loops is not obvious.

**Comment by tumic0** [comment] 2022-12-22 00:54
Duplicate of #164.

The situation is still the same. This would require non-trivial changes in the program and the resulting feature is not worth the effort for me.

**Closed by tumic0** 2022-12-22 00:54 UTC
