### ISSUE TITLE
Idea: Selectable List of loaded tracks for display

### ISSUE THREAD

**Issue by zavjah** [tumic0/GPXSee#365] opened 2021-04-21 07:29 UTC
Fist off all: WAHT A WANDERFULL SOFTWARE, thank you very much :-)

I am a big fan of data protection and thus record my tracks fully offline and do not want to publish them. With your software I can now browse all my tracks in easy. It even worked for all at once: 700 tracks loaded in just few second. EXCELENT, thank you.

One thing would do improve my use experience as I load several tracks at once all the time: a sidebar that lists the loaded tracks and each one of them can be selected/deselected for display in the map.

Maybe this is already in the pipeline, but if not, It'll be great feature.

thx,
zavjah

BTW: Can I somehow donate to support your project?

**Comment by tumic0** [comment] 2021-04-21 22:19
This has been discussed here several times, the last still open issue with this topic is #222. GPXSee was designed with the clear intent not to work with track lists as most other similar tools, but rather use the saved screen space for something more usable like the map or graphs. Some kind of track selection might be handy in some use cases, but it is not trivial to fit it into the current UI/UX and in general it has a very low priority for me.

Closing as duplicate of #222.

**Closed by tumic0** 2021-04-21 22:19 UTC

**Comment by zavjah** [comment] 2021-04-22 07:32
Hello tumic0,

thx for the hint and information. I do have one question concerning this statement from you: "not to work with track lists as most other similar tools". Can you name me some of those tool? That'l be great.

thx,
Zavjah

**Comment by tumic0** [comment] 2021-04-22 19:48
QMapShack, Routeconverter, Viking, MyTourbook, ... there are plenty of similar applications
