### ISSUE TITLE
UTC of a trackpoint

### ISSUE THREAD

**Issue by pbanys** [tumic0/GPXSee#495] opened 2023-05-02 10:11 UTC
Dear Developers,

It would be very useful to have a possibility to see the UTC timestamps of trackpoints. I often cut tracks into segments using an XML editor and this feature would significantly help at finding points.

Best regards,

Paweł

**Comment by tumic0** [comment] 2023-05-02 23:17
You can enable the absolute time of the slider in Data->Position info->Date/time

**Comment by pbanys** [comment] 2023-05-03 21:58
Please take a look at this GPX:
`<?xml version="1.0" encoding="UTF-8"?>
<gpx version="1.1">
  <trk>
    <trkseg>
      <trkpt lat="0" lon="0">
        <time>2021-02-13T11:00:00Z</time>
      </trkpt>
      <trkpt lat="1" lon="0">
        <time>2021-02-13T23:00:00Z</time>
      </trkpt>
    </trkseg>
    <trkseg>
      <trkpt lat="1" lon="0.01">
        <time>2021-02-23T09:00:00Z</time>
      </trkpt>
      <trkpt lat="1" lon="1">
        <time>2021-02-23T15:00:00Z</time>
      </trkpt>
    </trkseg>
  </trk>
</gpx>`
The slider indicates 18 hours of voyage. But the pause between the track segments is 10 days. Apart from that the dates shown on the track tip are 13 February and 14 February. What am I doing wrong?
Thank you for support!
Paweł

**Comment by tumic0** [comment] 2023-05-04 07:48
18 hours of voyage is correct, only the time of the track segments shall be counted when segments are enabled (the default). But the date is indeed wrong, i will investigate that further.

**Comment by tumic0** [comment] 2023-05-04 19:57
Fixed in 190a961242de9e18bf1a0ba532aad76afa22625b. You can still see some weird speed graph representation on the sample GPX file (when segments are disabled) that is caused by the "pause detection" algorithm not working properly on such artificial data with too few points. But that's another issue and it is questionable if it is worth some attempt to fix that...

**Closed by tumic0** 2023-05-04 19:57 UTC
