### ISSUE TITLE
Feature Request - shown single tracks on speed and elevation displays.

### ISSUE THREAD

**Issue by dgoadby** [tumic0/GPXSee#352] opened 2021-03-17 04:23 UTC
I make canal trips over many days. I create a single gpx file for the whole trip so the daily tracks are each identified as a new <trk>. The map shows these in different colours and I can see the whole trip - great! 

However, when I show the file the speed and elevation displays, all of the tracks are overlaid. Is it possible, to have a feature which showed just one track as a time? Maybe a shortcut for next and last track could be added too. Even better, the track selected on the map would be shown in the speed/elevation display. This would work with a "show one track" mode for these displays.

**Comment by tumic0** [comment] 2021-03-17 20:02
Duplicate of #222

**Closed by tumic0** 2021-03-17 20:02 UTC
