### ISSUE TITLE
Show grade when moving slider over altitude profile

### ISSUE THREAD

**Issue by Blittr** [tumic0/GPXSee#510] opened 2023-08-24 11:15 UTC
Hi Martin, is it possible to show the grade of an ascent or decent when moving the slider over the altitude profile?

**Comment by tumic0** [comment] 2023-08-25 10:29
Duplicate of #314

**Closed by tumic0** 2023-08-25 10:29 UTC

**Comment by Blittr** [comment] 2023-08-27 08:27
Hi Martin, I can't find an answer in the other issues you mentioned (#314 and #482)

**Comment by tumic0** [comment] 2023-08-27 15:05
Well, like for all other open wishes, the "answer" is that this feature may one day appear in GPXSee (if it would be totally out of scope, it would get closed), but it has not yet been implemented or even evaluated* (it may turn out, there are some problems that make it very hard to fit it to the current codebase or UI/UX).

*that's not the case here, I have already started fiddling with the grade, but it's not that easy to add it to GPXSee as it may look.

**Comment by Blittr** [comment] 2023-08-28 11:23
Apologies Martin, I had overlooked that #314 was still open. Thank you and best regards
