### ISSUE TITLE
[Feature Request] Absolute date/time in graph

### ISSUE THREAD

**Issue by arkanoid87** [tumic0/GPXSee#505] opened 2023-07-04 15:48 UTC
Currently the "Graph" menu presents you the option to pick "Distance" or "Time" as horizontal axis of graph.

If "Time" is selected, a relative time axis (in hours) is presented

It would be nice to add a "Date/Time" option to get absolute timeline of a recorded track. This would also work in tadem with "Data > Position info > date/time" option.

This would answer the question "which point on track is nearest to datetime YY-mm-dd hh-mm-ss" and also plays well with current zoomable timeline

**Comment by tumic0** [comment] 2023-07-04 16:43
Duplicate of #35.

**Closed by tumic0** 2023-07-04 16:43 UTC
