### ISSUE TITLE
List of gpx tours

### ISSUE THREAD

**Issue by alfi0815** [tumic0/GPXSee#440] opened 2022-06-06 09:04 UTC
I would like to display several tours at the same time. This is already working perfectly.
My wish would be to have a list of gpx tours. With a checkbox you could choose whether the tour is displayed or not.

**Comment by tumic0** [comment] 2022-06-06 20:34
More or less a duplicate of #222. See the discussion there.

**Closed by tumic0** 2022-06-06 20:34 UTC
