### ISSUE TITLE
Time graph does not account for gaps in recording

### ISSUE THREAD

**Issue by grubernd** [tumic0/GPXSee#304] opened 2020-08-16 11:20 UTC
Happens all the time when reception on the GPS is bad - in buildings, driving through tunnels or even under dense tree cover.

This makes the time graph pretty much useless because the user has to analyze the GPX file to make sure no gaps in recording are present.

Suggestion: use and show recorded times from the GPX file. If someone needs reliable relative times those can then be calculated from that.

**Comment by tumic0** [comment] 2020-08-16 14:16
Sorry, but I don't understand what you are trying to say. The recorded time is still "linear" regardless of any GPS signal outage and so are the graphs. If you don't want to have the intervals without the signal in your graphs/paths than use the part of the GPX specification that was designed for this purpose when recording your track - segments. GPXSee supports them.

For the absolute time graphs there is already an open issue - #35 so I'm closing this one as a duplicate.

**Closed by tumic0** 2020-08-16 14:16 UTC

**Comment by grubernd** [comment] 2020-08-16 20:31
Here, I condensed a GPX file from my Garmin etrex30 down to where it shows the bug I try to explain. (GPXsee v7.31)

The coordinates have been obfuscated, but the timestamps are real and the time between the two segments was when the GPS was inside a house with no reception, so that is as recorded.

Despite the massive jump in times between segments the timeline in GPXsee does not adjust. And while it may be very visible here, this happens all the time, making even the relative timeline rather useless because there is no visual reference as to where such a jump would occur.

```
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx>
<trk>
<name>Test</name>
<trkseg>
<trkpt lat="48.1111" lon="15.6"><ele>300</ele><time>2020-08-14T13:07:32Z</time></trkpt>
<trkpt lat="48.1112" lon="15.6"><ele>300</ele><time>2020-08-14T13:07:48Z</time></trkpt>
<trkpt lat="48.1113" lon="15.6"><ele>300</ele><time>2020-08-14T13:08:16Z</time></trkpt>
<trkpt lat="48.1114" lon="15.6"><ele>300</ele><time>2020-08-14T13:08:33Z</time></trkpt>
</trkseg>
<trkseg>
<trkpt lat="48.1117" lon="15.6"><ele>298.15</ele><time>2020-08-14T15:57:43Z</time></trkpt>
<trkpt lat="48.1118" lon="15.6"><ele>296.22</ele><time>2020-08-14T15:57:55Z</time></trkpt>
<trkpt lat="48.1119" lon="15.6"><ele>296.22</ele><time>2020-08-14T15:58:26Z</time></trkpt>
<trkpt lat="48.1120" lon="15.6"><ele>296.22</ele><time>2020-08-14T15:58:53Z</time></trkpt>
</trkseg>
</trk>
</gpx>
```

**Comment by tumic0** [comment] 2020-08-17 16:43
Ok, so the problem is, that you have segments in your data, but you don't want to handle them like such. To optionally disable track segment handling is a feature that is planned for GPXSee. Until then, you can achieve the desired behaviour by creating a copy of your GPX file with the segments removed (one segment wit all the track-points must still be present)

**Comment by grubernd** [comment] 2020-08-17 21:05
> Ok, so the problem is, that you have segments in your data, but you don't want to handle them like such

I didn't know about gpx segments until yesterday. ;-)

And well .. I was just trying to point out that the presentation in GPXsee might lead to unexpected behaviour for users because they can't see that there are segments at all and - more importantly - that time on the timeline is non-linear.

> To optionally disable track segment handling is a feature that is planned for GPXSee

That sounds great.

My personal preference would be to fill the gaps in the timeline  - just as they are filled with all the other singular datapoints right now. And I would make that the default setting. Yes, it breaks from the current behaviour, but then for a new or unaware user it follows the principle of least astonishment.
