### ISSUE TITLE
nmea dont work

### ISSUE THREAD

**Issue by k0styan3** [tumic0/GPXSee#488] opened 2023-03-24 17:21 UTC
![screenshot_gpxsee](https://user-images.githubusercontent.com/80951760/227595066-09062d94-135a-45a5-9190-2851a0b80c3e.png)
![screenshot_gpxsee1](https://user-images.githubusercontent.com/80951760/227595804-b555a06a-2338-41ac-b1e7-bfc65ce8bbd5.png)
![screenshot_gpxsee2](https://user-images.githubusercontent.com/80951760/227595811-f3b195a5-6a1b-4a28-a011-e104384045b5.png)
I apologize that there are no logs - I do not know how to remove them. but these files, nmea - I can't open any!!
windows 11,64 bit the program is the newest version

**Comment by tumic0** [comment] 2023-03-24 19:57
Please provide at least one of the NMEA files (You may have to ZIP them to be able to attach them to this issue).

**Comment by k0styan3** [comment] 2023-03-25 04:51
[nmea_device.zip](https://github.com/tumic0/GPXSee/files/11068019/nmea_device.zip)
good luck!

**Comment by tumic0** [comment] 2023-03-25 10:00
What is the source of this log files? Is it some real device or some conversion tool from another format? The problem is that the NMEA sentence lines exceed the line limit given by the NMEA standard (80 characters + CRLF). If there is some real device out there, that generates such broken NMEA files I can increase the limit in GPXSee, but if the file is from some conversion tool, than this tool should be fixed.

**Comment by k0styan3** [comment] 2023-03-25 13:45
This is google program gnss analysis tools. so the question can be closed. so this question should be forwarded to them. thanks for the help !  С уважением, Константин С.  От: Martin TůmaОтправлено: 25 марта 2023 г. в 12:00Кому: tumic0/GPXSeeКопия: k0styan3; AuthorТема: Re: [tumic0/GPXSee] nmea dont work (Issue #488) What is the source of this log files? Is it some real device or some conversion tool from another format? The problem is that the NMEA sentence lines exceed the line limit given by the NMEA standard (80 characters + CRLF). If there is some real device out there, that generates such broken NMEA files I can increase the limit in GPXSee, but if the file is from some conversion tool, than this tool should be fixed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by k0styan3** [comment] 2023-03-25 13:45
This is google program gnss analysis tools. so the question can be closed. so this question should be forwarded to them. thanks for the help ! С уважением, Константин С.  От: Martin TůmaОтправлено: 25 марта 2023 г. в 12:00Кому: tumic0/GPXSeeКопия: k0styan3; AuthorТема: Re: [tumic0/GPXSee] nmea dont work (Issue #488) What is the source of this log files? Is it some real device or some conversion tool from another format? The problem is that the NMEA sentence lines exceed the line limit given by the NMEA standard (80 characters + CRLF). If there is some real device out there, that generates such broken NMEA files I can increase the limit in GPXSee, but if the file is from some conversion tool, than this tool should be fixed.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Closed** 2023-04-02 17:00 UTC
