### ISSUE TITLE
[request] open two or more mbtiles map at the same time

### ISSUE THREAD

**Issue by 1stgongsin** [tumic0/GPXSee#204] opened 2019-04-29 08:32 UTC
Hello.
when the gpx track is out of the boundary of the opened map(mbtiles), gpx track is invisible.
It will be great GPXsee can open two or more mbtiles files at the same time
Thank you.

**Comment by tumic0** [comment] 2019-05-01 06:46
Duplicate of #178

**Closed by tumic0** 2019-05-01 06:46 UTC
