### ISSUE TITLE
Display time (instead of flight duration)

### ISSUE THREAD

**Issue by scls19fr** [tumic0/GPXSee#227] opened 2019-08-27 20:38 UTC
Hello,

currently plot displays altitude (or speed) vs flight duration.
Maybe an option should be available to display time instead.

Tooltip on altitude plot cursor display altitude and flight duration... maybe time could be added as a third line.

An other option could be to allow right click on this plot and have an option to change from flight duration to time as X-axis.

Kind regards

**Comment by tumic0** [comment] 2019-08-28 20:41
Duplicate of #35.

**Closed by tumic0** 2019-08-28 20:41 UTC
