### ISSUE TITLE
Base color setting is ignored by GPXSee v12.1 on Windows 11

### ISSUE THREAD

**Issue by McPringle** [tumic0/GPXSee#481] opened 2023-02-20 18:44 UTC
The base color is set to blue, but the track is still rendered in grey. It is very hard to spot the track on top of the map. Please take a look at my screenshot:

![grafik](https://user-images.githubusercontent.com/1254039/220179877-fd4dfdd8-7500-4879-adb3-7f6d1882a607.png)

**Comment by tumic0** [comment] 2023-02-20 20:58
If your data has some style information, than it overrides the base color setting (if you have "Use styles" enabled under "Data" which is the default). Can you please provide the data so I can decide whether this is a desired behaviour or a bug? (Some formats like GeoJSON have "implicit styles").

**Comment by tumic0** [comment] 2023-02-22 20:12
Closing as "not a bug". If there is no style (even implicit as e.g. in KML or GeoJSON) then reopen with the sample data.

**Closed by tumic0** 2023-02-22 20:12 UTC
