### ISSUE TITLE
Language GPXSee v. 7.19 setting MacOS

### ISSUE THREAD

**Issue by ihemsen** [tumic0/GPXSee#268] opened 2020-02-02 15:02 UTC
I have downloaded GPXSee version 7.19 for Mac. The program seems to be localised to Portugal
<img width="996" alt="Skjermbilde 2020-02-02 kl  15 35 41" src="https://user-images.githubusercontent.com/60574738/73609940-bdeb8900-45d2-11ea-98d9-2ca7be585b2a.png">. 
I see that similar bugs are reported (and closed) before, but this one seems to persist in the new versions. 
In the MacOS system settings I can select languages in individual SW. GPXSee claims only to support English. But as you can see, that is not the case.
<img width="1128" alt="Skjermbilde 2020-02-02 kl  15 59 49" src="https://user-images.githubusercontent.com/60574738/73610228-64388e00-45d5-11ea-8f7d-ab35ccbf886d.png">

**Comment by tumic0** [comment] 2020-02-02 16:16
GPXSee uses Qt's localisation system which is not based on "traditional lproj" files. OS X most probably uses the lproj files to get a list of available languages. Maybe some magic entry in the plist file could help here, but even if I would find a solution (which I didn't), I could not test it as on my old Mac with OS X 10.13 there is no such "per application language" feature.

**Comment by ihemsen** [comment] 2020-02-02 17:30
But strange that the Portuguese language was selected in Qt. I would be happy with English.

**Comment by tumic0** [comment] 2020-02-02 19:53
So there are two bugs in your report? One is the "wrong chosen" default language and the second the inability to specify a selected language for the application? Does it mean you got GPXSee in Portuguese without having this language in your preferences?!

**Comment by ihemsen** [comment] 2020-02-02 21:02
Yes, this could be two bugs in one. The most important one is that somehow Portuguese is used at all. Portuguese is far below Chinese in my list of preferred languages, and I don't read/speak Chinese. 
The second bug could be related to how Qt works and supports individual language settings in MacOS.

**Comment by tumic0** [comment] 2020-02-02 22:03
Well, if your list is the one on the first picture, you should get Norwegian. It works fine for me. The issue that was closed in the past was about English not selected as the fallback as the English qm file was missing. But in your list there are at least 4 other languages present in GPXSee that shall be selected prior to Portugese...

Maybe the problem is in the number of items on your list which is quite unusual. Anyway, there is not much I can do about it as GPXSee simply does what it should here and when there is a bug it is either in Qt (most probable) or in OS X.

**Comment by ihemsen** [comment] 2020-02-02 22:44
Ok. I deleted the unused entries in my list in system settings including Portuguese and restarted GPXSee. Now it is in Norwegian! This is not a common problem, but now also OpenSCAD changed from French to English. According to the about-OpenSCAD it also uses the Qt Toolkit library.

I guess the bug is there in Qt.

It is quite usual for the language list to be very long in MacOS. The default setting is almost as I had mine with a lot of languages I don't even understand. I have just moved some languages and not deleted or added any.

**Comment by ihemsen** [comment] 2020-02-02 22:54
Do you have a Qt account and can report the bug or should I give it a try?

**Comment by tumic0** [comment] 2020-02-03 22:11
I have a Qt account, but it is much better that someone who can reproduce the issue will report that. However note, that GPXSee uses Qt 5.9 on OS X because of [QTBUG-81791](https://bugreports.qt.io/browse/QTBUG-81791) so your report will not get much attention until you try it with the latest Qt version.

**Comment by ihemsen** [comment] 2020-02-03 22:39
I started filling out a bug report and noticed the same. Qt is 5.14 now... I will file the report and see what happens. Perhaps you could review it when it is filed to correct the project and component which I just have to guess...

**Comment by ihemsen** [comment] 2020-02-03 22:54
https://bugreports.qt.io/browse/QTBUG-81829

**Comment by tumic0** [comment] 2020-02-20 06:50
closing here

**Closed by tumic0** 2020-02-20 06:50 UTC
