### ISSUE TITLE
Slope of a part of the hill in degree

### ISSUE THREAD

**Issue by johai01** [tumic0/GPXSee#482] opened 2023-02-24 16:20 UTC
Hello, I like your app very much.  Since I do a lot of snowshoe tours and sometimes also on skis, I use the app to check the slope.  I would very much like to have this information in degrees (not percentage) in addition to the altitude and km display.  And not just for one point but for a stretch of a part of the mountain.  Unfortunately, this gradient in degrees is not solved satisfactorily in any app, which is why it still has to be measured on the paper map. best regards Johann

**Comment by tumic0** [comment] 2023-02-24 19:08
Duplicate of #314

Please use the already existing issue for further discussions.

**Closed by tumic0** 2023-02-24 19:08 UTC
