### ISSUE TITLE
show multiple graphs next to each other

### ISSUE THREAD

**Issue by doniks** [tumic0/GPXSee#535] opened 2024-03-28 14:10 UTC
GPXsee can load elevation, speed, power, heartrate and show in charts in tabs. One chart visible at a time. And while dragging the mouse through the chart, you can correlate to the location on the map. That's real nice. 

What would be even better is , if there would be a way to show *all* the charts at once, next to (or on vertically on top of) each other so I can also correlate, e.g., power and heartrate.

**Comment by tumic0** [comment] 2024-03-28 17:22
Duplicate of #14.
(Now with the Android version there are even more reasons why not to go this way)

**Closed by tumic0** 2024-03-28 17:22 UTC
